/**
 * Drone Database — ТТХ (Тактико-Технічні Характеристики)
 * Sources:
 *  - Appendix 1 & 3: "Памятка по применению FPV-дронов" (RF Military Manual, 2024)
 *  - CSD Drone Databook, Bard College (Dan Gettinger, 2020)
 *  - dronecalc/v1 database — 125 platforms (open-source data, 2024–2026)
 *  - DRONESBIIBLE Engineering+Warfare catalogue
 */

export type DroneCategory =
  | "fpv-attack"
  | "isr-multirotor"
  | "isr-fixed"
  | "male";

export interface DroneSpec {
  id: string;
  name: string;
  manufacturer: string;
  country: string;
  category: DroneCategory;
  /** kg */
  massKg: number;
  /** kg */
  payloadKg?: number;
  /** minutes */
  flightTimeMin?: number;
  /** km */
  rangeKm?: number;
  /** km/h */
  maxSpeedKmh?: number;
  /** meters */
  maxAltM?: number;
  /** e.g. "GPS, GLONASS, Galileo" */
  gnss?: string;
  /** MHz, e.g. "868/915" */
  controlFreqMhz?: string;
  /** GHz */
  videoFreqGhz?: number;
  /** mAh */
  batteryMah?: number;
  /** m/s */
  maxWindMs?: number;
  /** e.g. "−10…+40" */
  tempRangeCelsius?: string;
  /** camera description */
  camera?: string;
  /** meters */
  wingspanM?: number;
  notes?: string;
  source: string;
}

// ---------------------------------------------------------------------------
// FPV Attack Drones
// ---------------------------------------------------------------------------
export const FPV_ATTACK: DroneSpec[] = [
  // ── RF FPV (Appendix 1, RF Military Manual 2024) ──
  {
    id: "bumerang",
    name: "Бумеранг",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.2,
    payloadKg: 3.5,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 180,
    controlFreqMhz: "433/868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "skvorets",
    name: "Скворець",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.3,
    payloadKg: 2.2,
    flightTimeMin: 11,
    rangeKm: 10,
    maxSpeedKmh: 100,
    controlFreqMhz: "433/868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "xl-10",
    name: "XL-10",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.2,
    payloadKg: 3.5,
    flightTimeMin: 12,
    rangeKm: 10,
    maxSpeedKmh: 140,
    controlFreqMhz: "868/915/2400",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "kuryer",
    name: "Курьер (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.3,
    payloadKg: 3.5,
    flightTimeMin: 13,
    rangeKm: 10,
    maxSpeedKmh: 60,
    controlFreqMhz: "868/915/2400",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "pirania-7",
    name: "Піранья-7 (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.36,
    payloadKg: 2.5,
    flightTimeMin: 13,
    rangeKm: 7,
    maxSpeedKmh: 125,
    controlFreqMhz: "868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "pirania-10",
    name: "Піранья-10 (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.49,
    payloadKg: 4.5,
    flightTimeMin: 11,
    rangeKm: 13,
    maxSpeedKmh: 140,
    controlFreqMhz: "868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "khimera-7",
    name: "Химера-7 (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.2,
    payloadKg: 3.0,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 180,
    controlFreqMhz: "433/868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "pvkh-1",
    name: "ПВХ-1 (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.2,
    payloadKg: 3.0,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 180,
    controlFreqMhz: "868/915",
    videoFreqGhz: 5.8,
    source: "RF FPV Manual 2024, App. 1",
  },
  {
    id: "zmiyo-horynych-7",
    name: 'FPV "Зміє-Горинич" 7"',
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 1.4,
    payloadKg: 0.7,
    flightTimeMin: 12,
    rangeKm: 7,
    maxSpeedKmh: 110,
    batteryMah: 2200,
    videoFreqGhz: 5.8,
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-fpv-combo",
    name: "DJI FPV Combo",
    manufacturer: "DJI",
    country: "CN",
    category: "fpv-attack",
    massKg: 0.795,
    flightTimeMin: 20,
    rangeKm: 10,
    maxSpeedKmh: 140,
    batteryMah: 2000,
    videoFreqGhz: 5.8,
    notes: "Комерційний FPV, адаптується для камікадзе",
    source: "dronecalc/v1 database",
  },
  // ── Ukrainian FPV ──
  {
    id: "fpv-5in",
    name: 'FPV 5" стандартний',
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 0.9,
    payloadKg: 0.5,
    flightTimeMin: 8,
    rangeKm: 5,
    maxSpeedKmh: 120,
    batteryMah: 1500,
    source: "dronecalc/v1 database",
  },
  {
    id: "fpv-7in-kamikadze",
    name: 'FPV 7" камікадзе',
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 1.5,
    payloadKg: 0.8,
    flightTimeMin: 12,
    rangeKm: 8,
    maxSpeedKmh: 120,
    batteryMah: 1300,
    source: "dronecalc/v1 database",
  },
  {
    id: "fpv-10in-shpak",
    name: 'FPV 10" (Shpak)',
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 2.0,
    payloadKg: 5.0,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 150,
    batteryMah: 6000,
    source: "dronecalc/v1 database",
  },
  {
    id: "fpv-13in-bomber",
    name: 'FPV 13" важкий бомбер',
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 5.0,
    payloadKg: 4.5,
    flightTimeMin: 20,
    rangeKm: 12,
    maxSpeedKmh: 80,
    batteryMah: 8000,
    source: "dronecalc/v1 database",
  },
  {
    id: "vyriy-max-15",
    name: "VYRIY MAX 15",
    manufacturer: "VYRIY",
    country: "UA",
    category: "fpv-attack",
    massKg: 8.0,
    payloadKg: 8.0,
    flightTimeMin: 20,
    rangeKm: 30,
    maxSpeedKmh: 100,
    batteryMah: 16000,
    source: "dronecalc/v1 database",
  },
  {
    id: "hornet-queen",
    name: "Hornet Queen (Wild Hornets)",
    manufacturer: "Wild Hornets",
    country: "UA",
    category: "fpv-attack",
    massKg: 18.0,
    payloadKg: 9.5,
    flightTimeMin: 37,
    rangeKm: 17,
    maxSpeedKmh: 60,
    notes: "Гексакоптер 15\", ЗЛІТНА маса 18 кг, 65% компонентів — українські",
    source: "dronecalc/v1 database",
  },
  {
    id: "fpv-18in-fiber",
    name: 'FPV 18" волоконно-оптичний',
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 5.0,
    payloadKg: 6.0,
    flightTimeMin: 25,
    rangeKm: 50,
    maxSpeedKmh: 120,
    batteryMah: 20000,
    notes: "Волоконно-оптичне керування, повна стійкість до РЕБ",
    source: "dronecalc/v1 database",
  },
  {
    id: "caddx-vista-fpv",
    name: "Caddx Vista FPV",
    manufacturer: "Caddx",
    country: "CN",
    category: "fpv-attack",
    massKg: 1.2,
    payloadKg: 0.5,
    flightTimeMin: 15,
    rangeKm: 3,
    maxSpeedKmh: 180,
    batteryMah: 1500,
    videoFreqGhz: 5.8,
    source: "dronecalc/v1 database",
  },
  {
    id: "baba-yaga",
    name: "FPV «Баба Яга» (аграрний)",
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 15.0,
    payloadKg: 10.0,
    flightTimeMin: 35,
    rangeKm: 10,
    maxSpeedKmh: 50,
    batteryMah: 22000,
    notes: "Модифікований DJI Agras, нічні атаки, гексакоптер",
    source: "dronecalc/v1 database",
  },
  {
    id: "vampire-skyfall",
    name: "Vampire (SkyFall)",
    manufacturer: "SkyFall",
    country: "UA",
    category: "fpv-attack",
    massKg: 20.0,
    payloadKg: 15.0,
    flightTimeMin: 37,
    rangeKm: 22,
    maxSpeedKmh: 80,
    batteryMah: 22000,
    notes: "Гексакоптер-бомбер #1 ЗСУ 2025. Тепловізор.",
    source: "dronecalc/v1 database",
  },
  {
    id: "r18-octocopter",
    name: "R18 Octocopter (UA Dynamics)",
    manufacturer: "UA Dynamics",
    country: "UA",
    category: "fpv-attack",
    massKg: 10.0,
    payloadKg: 5.0,
    flightTimeMin: 30,
    rangeKm: 10,
    maxSpeedKmh: 50,
    batteryMah: 22000,
    notes: "Важкий октокоптер-бомбер ЗСУ #1 2023, тепловізор",
    source: "dronecalc/v1 database",
  },
  {
    id: "ring-kvs",
    name: "Ring / KVS (РФ FPV)",
    manufacturer: "—",
    country: "RU",
    category: "fpv-attack",
    massKg: 5.0,
    payloadKg: 3.0,
    flightTimeMin: 40,
    rangeKm: 50,
    maxSpeedKmh: 120,
    notes: "Кільцеве крило, волоконно-оптичне керування. Виявлено 03.2026",
    source: "dronecalc/v1 database",
  },
  {
    id: "ptashka-18",
    name: "Пташка-18 (NextGen Defense)",
    manufacturer: "NextGen Defense",
    country: "UA",
    category: "fpv-attack",
    massKg: 9.0,
    payloadKg: 5.0,
    flightTimeMin: 25,
    rangeKm: 20,
    maxSpeedKmh: 140,
    notes: '18" FPV, волоконно-оптика, захист від РЕБ, warhead 5+ кг',
    source: "dronecalc/v1 database",
  },
  {
    id: "shrike-interceptor",
    name: "Shrike (UA Interceptor)",
    manufacturer: "—",
    country: "UA",
    category: "fpv-attack",
    massKg: 1.5,
    payloadKg: 0.5,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 200,
    notes: "FPV-перехоплювач дрон-проти-дрона",
    source: "dronecalc/v1 database",
  },
  {
    id: "switchblade-300",
    name: "Switchblade 300",
    manufacturer: "AeroVironment",
    country: "US",
    category: "fpv-attack",
    massKg: 2.5,
    payloadKg: 2.0,
    flightTimeMin: 15,
    rangeKm: 10,
    maxSpeedKmh: 157,
    batteryMah: 3000,
    notes: "Барражуючий боєприпас, тандемна БЧ, оператор може скасувати удар",
    source: "dronecalc/v1 database",
  },
  {
    id: "kargu-2",
    name: "STM Kargu-2",
    manufacturer: "STM",
    country: "TR",
    category: "fpv-attack",
    massKg: 7.0,
    payloadKg: 1.5,
    flightTimeMin: 30,
    rangeKm: 5,
    maxSpeedKmh: 130,
    notes: "Автономний барражуючий боєприпас з AI-розпізнаванням (Лівія 2020)",
    source: "dronecalc/v1 database",
  },
];

// ---------------------------------------------------------------------------
// ISR Multirotors — Commercial & military reconnaissance platforms
// ---------------------------------------------------------------------------
export const ISR_MULTIROTOR: DroneSpec[] = [
  // ── App. 3 RF Manual ──
  {
    id: "dji-air-2s",
    name: "DJI Air 2S",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.595,
    flightTimeMin: 31,
    rangeKm: 12,
    maxSpeedKmh: 68,
    maxAltM: 5000,
    batteryMah: 3500,
    maxWindMs: 10.7,
    gnss: "GPS, GLONASS, Galileo",
    tempRangeCelsius: "0…+40",
    camera: "1\" CMOS 5.4K OcuSync 3",
    source: "RF FPV Manual 2024, App. 3",
  },
  {
    id: "dji-mavic-pro-platinum",
    name: "DJI Mavic Pro Platinum",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.734,
    flightTimeMin: 30,
    rangeKm: 7,
    maxSpeedKmh: 65,
    maxAltM: 5000,
    batteryMah: 3830,
    maxWindMs: 10,
    gnss: "GPS, GLONASS",
    tempRangeCelsius: "0…+40",
    camera: "4K OcuSync",
    source: "RF FPV Manual 2024, App. 3",
  },
  {
    id: "autel-evo",
    name: "Autel EVO",
    manufacturer: "Autel Robotics",
    country: "US",
    category: "isr-multirotor",
    massKg: 0.595,
    flightTimeMin: 31,
    rangeKm: 12,
    maxSpeedKmh: 68,
    maxAltM: 5000,
    batteryMah: 3500,
    maxWindMs: 10.7,
    gnss: "GPS, GLONASS, Galileo",
    tempRangeCelsius: "0…+40",
    camera: "4K",
    source: "RF FPV Manual 2024, App. 3",
  },
  // ── DJI line-up ──
  {
    id: "dji-mavic-3",
    name: "DJI Mavic 3",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.895,
    flightTimeMin: 46,
    rangeKm: 25,
    maxSpeedKmh: 75,
    maxAltM: 6000,
    batteryMah: 5000,
    gnss: "GPS, GLONASS, Galileo",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-mavic-3t",
    name: "DJI Mavic 3T (тепловізійний)",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.92,
    flightTimeMin: 45,
    rangeKm: 25,
    maxSpeedKmh: 75,
    maxAltM: 6000,
    batteryMah: 5000,
    gnss: "GPS, GLONASS, Galileo",
    camera: "Тепловізор 640px + 4K wide",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-mavic-3e",
    name: "DJI Mavic 3 Enterprise",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.915,
    flightTimeMin: 45,
    rangeKm: 15,
    maxSpeedKmh: 75,
    maxAltM: 6000,
    batteryMah: 5000,
    notes: "Кріплення аксесуарів, RTK, гучномовець/прожектор",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-matrice-30t",
    name: "DJI Matrice 30T",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 3.77,
    flightTimeMin: 41,
    rangeKm: 15,
    maxSpeedKmh: 82,
    maxAltM: 7000,
    batteryMah: 5880,
    gnss: "GPS, GLONASS, Galileo, BeiDou",
    tempRangeCelsius: "-20…+50",
    camera: "48 Мп + тепловізор 640px",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-mini-4-pro",
    name: "DJI Mini 4 Pro",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.249,
    flightTimeMin: 34,
    rangeKm: 20,
    maxSpeedKmh: 57,
    batteryMah: 2590,
    gnss: "GPS, GLONASS, Galileo",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-mini-2",
    name: "DJI Mini 2",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.249,
    flightTimeMin: 31,
    rangeKm: 10,
    maxSpeedKmh: 57,
    batteryMah: 2250,
    gnss: "GPS, GLONASS",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-neo",
    name: "DJI Neo",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.135,
    flightTimeMin: 18,
    rangeKm: 8,
    maxSpeedKmh: 57,
    batteryMah: 1100,
    camera: "4K 60fps",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-mavic-air",
    name: "DJI Mavic Air",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 0.43,
    flightTimeMin: 21,
    rangeKm: 10,
    maxSpeedKmh: 68,
    batteryMah: 2375,
    gnss: "GPS, GLONASS",
    camera: "4K 3-осьова стабілізація",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-phantom-3",
    name: "DJI Phantom 3 Standard",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 1.216,
    flightTimeMin: 25,
    rangeKm: 8,
    maxSpeedKmh: 57,
    batteryMah: 4480,
    gnss: "GPS, GLONASS",
    camera: "2.7K відео",
    source: "dronecalc/v1 database",
  },
  {
    id: "autel-evo-max-4t",
    name: "Autel EVO Max 4T",
    manufacturer: "Autel Robotics",
    country: "CN",
    category: "isr-multirotor",
    massKg: 1.58,
    flightTimeMin: 42,
    rangeKm: 20,
    maxSpeedKmh: 72,
    batteryMah: 7100,
    gnss: "GPS, GLONASS, Galileo, BeiDou",
    camera: "50 Мп + тепловізор FLIR 640px + LiDAR",
    source: "dronecalc/v1 database",
  },
  {
    id: "dji-agras-t50",
    name: "DJI Agras T50",
    manufacturer: "DJI",
    country: "CN",
    category: "isr-multirotor",
    massKg: 47.5,
    payloadKg: 50.0,
    flightTimeMin: 28,
    rangeKm: 5,
    maxSpeedKmh: 50,
    batteryMah: 30000,
    notes: "Сільськогосподарський, адаптується для скидань ВОГ/РПГ",
    source: "dronecalc/v1 database",
  },
  {
    id: "skydio-2plus",
    name: "Skydio 2+",
    manufacturer: "Skydio",
    country: "US",
    category: "isr-multirotor",
    massKg: 0.8,
    flightTimeMin: 27,
    rangeKm: 7,
    maxSpeedKmh: 58,
    batteryMah: 4280,
    notes: "Автономне уникнення перешкод 360° Nvidia Xavier. ВПС США.",
    source: "dronecalc/v1 database",
  },
  {
    id: "parrot-anafi-ai",
    name: "Parrot ANAFI Ai",
    manufacturer: "Parrot",
    country: "INT",
    category: "isr-multirotor",
    massKg: 0.9,
    flightTimeMin: 32,
    rangeKm: 32,
    maxSpeedKmh: 55,
    batteryMah: 6400,
    gnss: "GPS, GLONASS, Galileo",
    notes: "NATO сертифікат, відкрите ANAFI API SDK",
    source: "dronecalc/v1 database",
  },
  {
    id: "rq-20-puma",
    name: "RQ-20 Puma AE",
    manufacturer: "AeroVironment",
    country: "US",
    category: "isr-multirotor",
    massKg: 5.9,
    flightTimeMin: 120,
    rangeKm: 15,
    maxSpeedKmh: 83,
    batteryMah: 8000,
    notes: "Посадка на воду, EO/IR підвіс, ВМФ США та ЗСУ",
    source: "dronecalc/v1 database",
  },
  {
    id: "aev-snipe-nano",
    name: "Aerovironment Snipe Nano",
    manufacturer: "AeroVironment",
    country: "US",
    category: "isr-multirotor",
    massKg: 0.1,
    flightTimeMin: 15,
    rangeKm: 1,
    maxSpeedKmh: 40,
    batteryMah: 350,
    notes: "Нано-БПЛА для дій у приміщеннях, 10 cm розмах крил",
    source: "dronecalc/v1 database",
  },
  {
    id: "crazyflie-2",
    name: "Crazyflie 2.1 (Bitcraze)",
    manufacturer: "Bitcraze",
    country: "INT",
    category: "isr-multirotor",
    massKg: 0.027,
    flightTimeMin: 7,
    rangeKm: 0.1,
    maxSpeedKmh: 30,
    batteryMah: 250,
    notes: "Open-source nano-квадрокоптер (R&D, swarm LLM). STM32F405.",
    source: "dronecalc/v1 database",
  },
];

// ---------------------------------------------------------------------------
// ISR Fixed-wing & Loitering Munitions
// ---------------------------------------------------------------------------
export const ISR_FIXED: DroneSpec[] = [
  // ── Loitering munitions ──
  {
    id: "harop",
    name: "Harop (loitering munition)",
    manufacturer: "IAI",
    country: "IL",
    category: "isr-fixed",
    massKg: 135,
    payloadKg: 23,
    flightTimeMin: 540,
    rangeKm: 200,
    wingspanM: 3,
    notes: "Барражуючий боєприпас, пасивна ГСН (ЕМВ), 9 год барражування",
    source: "CSD Drone Databook 2020",
  },
  {
    id: "lancet-3",
    name: "Lancet-3 / «Ланцет»",
    manufacturer: "ZALA Aero",
    country: "RU",
    category: "isr-fixed",
    massKg: 12,
    payloadKg: 3.0,
    flightTimeMin: 40,
    rangeKm: 40,
    maxSpeedKmh: 300,
    batteryMah: 4400,
    notes: "Барражуючий боєприпас РФ, тандемна кумулятивна БЧ",
    source: "dronecalc/v1 database",
  },
  {
    id: "lancet-1",
    name: "Lancet-1",
    manufacturer: "ZALA Aero",
    country: "RU",
    category: "isr-fixed",
    massKg: 5,
    payloadKg: 1.0,
    flightTimeMin: 30,
    rangeKm: 25,
    maxSpeedKmh: 110,
    batteryMah: 4000,
    notes: "Менший варіант Lancet, проти легкоброньованої техніки",
    source: "dronecalc/v1 database",
  },
  {
    id: "kub-bla",
    name: "Kub-BLA (ZALA Aero)",
    manufacturer: "ZALA Aero",
    country: "RU",
    category: "isr-fixed",
    massKg: 40,
    payloadKg: 3.0,
    flightTimeMin: 30,
    rangeKm: 40,
    maxSpeedKmh: 130,
    notes: "Барражуючий боєприпас РФ, 3 кг БЧ, аналог Switchblade",
    source: "dronecalc/v1 database",
  },
  {
    id: "switchblade-600",
    name: "Switchblade 600",
    manufacturer: "AeroVironment",
    country: "US",
    category: "isr-fixed",
    massKg: 22.7,
    payloadKg: 5.0,
    flightTimeMin: 40,
    rangeKm: 40,
    maxSpeedKmh: 185,
    batteryMah: 10000,
    notes: "Великий барражуючий боєприпас, кумулятивна БЧ проти танків",
    source: "dronecalc/v1 database",
  },
  {
    id: "phoenix-ghost",
    name: "Phoenix Ghost (AEVEX)",
    manufacturer: "AEVEX Aerospace",
    country: "US",
    category: "isr-fixed",
    massKg: 5.9,
    payloadKg: 8.0,
    flightTimeMin: 360,
    rangeKm: 400,
    maxSpeedKmh: 200,
    notes: "Барражуючий боєприпас 6+ год, нічне бачення, атака зверху",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-136",
    name: "Shahed-136 / «Герань-2»",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 200,
    payloadKg: 40.0,
    flightTimeMin: 584,
    rangeKm: 1800,
    maxSpeedKmh: 185,
    wingspanM: 2.5,
    notes: "Поршневий двигун, Х-подібне крило, летить зграями",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-131",
    name: "Shahed-131 / «Герань-1»",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 36,
    payloadKg: 15.0,
    flightTimeMin: 318,
    rangeKm: 900,
    maxSpeedKmh: 170,
    notes: "Менший варіант Shahed-136, БЧ 15 кг",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-238",
    name: "Shahed-238 (реактивний)",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 250,
    payloadKg: 50.0,
    flightTimeMin: 450,
    rangeKm: 1500,
    maxSpeedKmh: 650,
    notes: "Реактивна версія Shahed-136, турбореактивний двигун",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-191",
    name: "Shahed-191 Saeqeh",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 900,
    payloadKg: 500.0,
    flightTimeMin: 720,
    rangeKm: 2000,
    maxSpeedKmh: 650,
    wingspanM: 10,
    notes: "Іранський стелс UCAV flying wing, аналог RQ-170",
    source: "dronecalc/v1 database",
  },
  {
    id: "qasef-2k",
    name: "Qasef-2K",
    manufacturer: "Ansar Allah",
    country: "IR",
    category: "isr-fixed",
    massKg: 90,
    payloadKg: 30.0,
    flightTimeMin: 60,
    rangeKm: 150,
    maxSpeedKmh: 180,
    notes: "Барражуючий боєприпас Хуті/Ірану, атаки Саудівської Аравії",
    source: "dronecalc/v1 database",
  },
  {
    id: "ababil-3",
    name: "HESA Ababil-3",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 83,
    payloadKg: 45.0,
    flightTimeMin: 270,
    rangeKm: 150,
    maxSpeedKmh: 300,
    notes: "Іранський тактичний БПЛА-камікадзе, передвісник Shahed-136",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-101",
    name: "Shahed-101",
    manufacturer: "HESA",
    country: "IR",
    category: "isr-fixed",
    massKg: 30,
    payloadKg: 5.0,
    flightTimeMin: 90,
    rangeKm: 100,
    maxSpeedKmh: 200,
    notes: "Малий барражуючий боєприпас, аналог RQ-170",
    source: "dronecalc/v1 database",
  },
  // ── RF fixed-wing ──
  {
    id: "orlan-10",
    name: "Orlan-10",
    manufacturer: "STRC",
    country: "RU",
    category: "isr-fixed",
    massKg: 14,
    payloadKg: 5.0,
    flightTimeMin: 960,
    rangeKm: 120,
    maxSpeedKmh: 150,
    notes: "Бензиновий двигун Saito, коригує вогонь артилерії та РСЗВ",
    source: "dronecalc/v1 database",
  },
  {
    id: "orlan-30",
    name: "Orlan-30",
    manufacturer: "STRC",
    country: "RU",
    category: "isr-fixed",
    massKg: 25,
    payloadKg: 8.0,
    flightTimeMin: 600,
    rangeKm: 150,
    maxSpeedKmh: 180,
    notes: "Лазерний далекомір + ретранслятор, наводить ПТРК",
    source: "dronecalc/v1 database",
  },
  {
    id: "zala-421-16e5",
    name: "ZALA 421-16E5",
    manufacturer: "ZALA Aero",
    country: "RU",
    category: "isr-fixed",
    massKg: 2.5,
    payloadKg: 0.5,
    flightTimeMin: 40,
    rangeKm: 15,
    maxSpeedKmh: 130,
    batteryMah: 14000,
    source: "dronecalc/v1 database",
  },
  {
    id: "zala-421-08m",
    name: "ZALA 421-08M",
    manufacturer: "ZALA Aero",
    country: "RU",
    category: "isr-fixed",
    massKg: 2.7,
    payloadKg: 0.5,
    flightTimeMin: 90,
    rangeKm: 15,
    maxSpeedKmh: 130,
    batteryMah: 10000,
    source: "dronecalc/v1 database",
  },
  {
    id: "granat-4",
    name: "Granat-4",
    manufacturer: "STRC",
    country: "RU",
    category: "isr-fixed",
    massKg: 14,
    payloadKg: 3.5,
    flightTimeMin: 240,
    rangeKm: 120,
    maxSpeedKmh: 130,
    batteryMah: 18000,
    source: "dronecalc/v1 database",
  },
  {
    id: "supercam-s350",
    name: "Supercam S350",
    manufacturer: "Supercam",
    country: "RU",
    category: "isr-fixed",
    massKg: 3.5,
    payloadKg: 1.0,
    flightTimeMin: 240,
    rangeKm: 100,
    maxSpeedKmh: 120,
    batteryMah: 16000,
    source: "dronecalc/v1 database",
  },
  {
    id: "eleron-3sv",
    name: "Eleron-3SV",
    manufacturer: "ENICS",
    country: "RU",
    category: "isr-fixed",
    massKg: 2.8,
    payloadKg: 1.0,
    flightTimeMin: 90,
    rangeKm: 25,
    maxSpeedKmh: 130,
    batteryMah: 14000,
    source: "dronecalc/v1 database",
  },
  {
    id: "korsar",
    name: "Korsar",
    manufacturer: "ROELEKTRONIKA",
    country: "RU",
    category: "isr-fixed",
    massKg: 14.5,
    payloadKg: 6.0,
    flightTimeMin: 480,
    rangeKm: 120,
    maxSpeedKmh: 150,
    notes: "Катапульта, ЕО/ТПВ підвіс",
    source: "dronecalc/v1 database",
  },
  // ── Ukrainian fixed-wing ──
  {
    id: "a1-sm-furia",
    name: "A1-SM Furia (Athlon Avia)",
    manufacturer: "Athlon Avia",
    country: "UA",
    category: "isr-fixed",
    massKg: 6.5,
    payloadKg: 1.0,
    flightTimeMin: 240,
    rangeKm: 50,
    maxSpeedKmh: 150,
    batteryMah: 42000,
    notes: "Складний корпус, запуск з пікапу, камікадзе/розвідка",
    source: "dronecalc/v1 database",
  },
  {
    id: "leleka-100",
    name: "Лелека-100 (DeViRo)",
    manufacturer: "DeViRo",
    country: "UA",
    category: "isr-fixed",
    massKg: 2.5,
    flightTimeMin: 300,
    rangeKm: 80,
    maxSpeedKmh: 120,
    maxAltM: 1000,
    batteryMah: 14000,
    notes: "Катапульта/парашут, стійкість до РЕБ, радіус 80 км",
    source: "dronecalc/v1 database",
  },
  {
    id: "ram-ii",
    name: "RAM II UAV (DeViRo)",
    manufacturer: "DeViRo",
    country: "UA",
    category: "isr-fixed",
    massKg: 3.5,
    payloadKg: 5.0,
    flightTimeMin: 60,
    rangeKm: 30,
    maxSpeedKmh: 130,
    batteryMah: 14000,
    notes: "Камікадзе на базі Лелека-100, мобільна катапульта",
    source: "dronecalc/v1 database",
  },
  {
    id: "spectator-m1",
    name: "Spectator M-1",
    manufacturer: "—",
    country: "UA",
    category: "isr-fixed",
    massKg: 4.5,
    payloadKg: 1.5,
    flightTimeMin: 120,
    rangeKm: 50,
    maxSpeedKmh: 120,
    notes: "ЕО/ІЧ підвіс, катапульта, парашутна посадка",
    source: "dronecalc/v1 database",
  },
  {
    id: "shark-hero",
    name: "Shark (Hero Systems)",
    manufacturer: "Hero Systems",
    country: "UA",
    category: "isr-fixed",
    massKg: 5.5,
    payloadKg: 2.0,
    flightTimeMin: 270,
    rangeKm: 75,
    maxSpeedKmh: 180,
    notes: "Стратегічний розвідник, морські операції, 4.5 год",
    source: "dronecalc/v1 database",
  },
  {
    id: "punisher-uas",
    name: "Punisher UAS (UA Dynamics)",
    manufacturer: "UA Dynamics",
    country: "UA",
    category: "isr-fixed",
    massKg: 6.7,
    payloadKg: 3.0,
    flightTimeMin: 180,
    rangeKm: 100,
    maxSpeedKmh: 130,
    notes: "3 бомби ТП-1 (1.5 кг кожна), катапультний запуск",
    source: "dronecalc/v1 database",
  },
  {
    id: "furia-ua",
    name: "Фурія (UA Dynamics)",
    manufacturer: "UA Dynamics",
    country: "UA",
    category: "isr-fixed",
    massKg: 5.5,
    flightTimeMin: 180,
    rangeKm: 50,
    maxSpeedKmh: 100,
    source: "dronecalc/v1 database",
  },
  {
    id: "valkyria-ua",
    name: "Валькірія-UA",
    manufacturer: "Warbirds",
    country: "UA",
    category: "isr-fixed",
    massKg: 18,
    payloadKg: 5,
    flightTimeMin: 240,
    rangeKm: 100,
    maxSpeedKmh: 120,
    source: "dronecalc/v1 database",
  },
  // ── Polish / NATO ──
  {
    id: "flyeye",
    name: "WB Group FlyEye",
    manufacturer: "WB Electronics",
    country: "PL",
    category: "isr-fixed",
    massKg: 11,
    payloadKg: 1.0,
    flightTimeMin: 180,
    rangeKm: 30,
    maxSpeedKmh: 140,
    notes: "Польський тактичний БПЛА, поставлений Україні",
    source: "dronecalc/v1 database",
  },
  {
    id: "rq-11b-raven",
    name: "RQ-11B Raven",
    manufacturer: "AeroVironment",
    country: "US",
    category: "isr-fixed",
    massKg: 1.9,
    payloadKg: 0.2,
    flightTimeMin: 60,
    rangeKm: 10,
    maxSpeedKmh: 65,
    batteryMah: 5500,
    notes: "Міні-БПЛА розвідки, ручний запуск, NATO стандарт",
    source: "dronecalc/v1 database",
  },
  {
    id: "rq-7b-shadow",
    name: "RQ-7B Shadow 200",
    manufacturer: "TextronSystems",
    country: "US",
    category: "isr-fixed",
    massKg: 170,
    payloadKg: 27.0,
    flightTimeMin: 480,
    rangeKm: 125,
    maxSpeedKmh: 204,
    wingspanM: 6,
    notes: "Тактичний БПЛА батальйонного рівня, Wankel AR801",
    source: "dronecalc/v1 database",
  },
  {
    id: "altius-600",
    name: "Altius-600 (Area-I)",
    manufacturer: "Area-I",
    country: "US",
    category: "isr-fixed",
    massKg: 27.2,
    payloadKg: 12.7,
    flightTimeMin: 270,
    rangeKm: 440,
    maxSpeedKmh: 278,
    notes: "Запуск з тубуса, MADL зв'язок, передові підрозділи",
    source: "dronecalc/v1 database",
  },
  {
    id: "wasp-ae",
    name: "Aerovironment Wasp AE",
    manufacturer: "AeroVironment",
    country: "US",
    category: "isr-fixed",
    massKg: 0.43,
    payloadKg: 0.2,
    flightTimeMin: 50,
    rangeKm: 5,
    maxSpeedKmh: 65,
    batteryMah: 3000,
    notes: "Малий тактичний БПЛА, тихий польот, ЦРУ і SOCOM",
    source: "dronecalc/v1 database",
  },
  // ── Israeli fixed-wing ──
  {
    id: "iai-bird-eye-650d",
    name: "IAI Bird-Eye 650D",
    manufacturer: "IAI",
    country: "IL",
    category: "isr-fixed",
    massKg: 11,
    payloadKg: 2.5,
    flightTimeMin: 240,
    rangeKm: 60,
    maxSpeedKmh: 140,
    notes: "Компактний тактичний БПЛА, EO/IR, батальйонний рівень",
    source: "dronecalc/v1 database",
  },
  // ── Survey VTOL ──
  {
    id: "trinity-f90plus",
    name: "Quantum Systems Trinity F90+",
    manufacturer: "Quantum Systems",
    country: "INT",
    category: "isr-fixed",
    massKg: 6.5,
    payloadKg: 1.8,
    flightTimeMin: 90,
    rangeKm: 100,
    maxSpeedKmh: 110,
    notes: "VTOL фіксоване крило, LiDAR/фотограмметрія",
    source: "dronecalc/v1 database",
  },
  {
    id: "wingtra-gen2",
    name: "WingtraOne GEN II",
    manufacturer: "Wingtra",
    country: "INT",
    category: "isr-fixed",
    massKg: 3.7,
    payloadKg: 0.8,
    flightTimeMin: 59,
    rangeKm: 60,
    maxSpeedKmh: 90,
    notes: "VTOL tail-sitter, PPK/RTK, 3D картографування",
    source: "dronecalc/v1 database",
  },
];

// ---------------------------------------------------------------------------
// MALE / Strike UAV
// ---------------------------------------------------------------------------
export const MILITARY_UAV: DroneSpec[] = [
  // ── Original CSD Databook ──
  {
    id: "wing-loong-i",
    name: "Wing Loong I",
    manufacturer: "AVIC",
    country: "CN",
    category: "male",
    massKg: 1250,
    payloadKg: 200,
    flightTimeMin: 1200,
    rangeKm: 4000,
    maxSpeedKmh: 180,
    wingspanM: 14,
    source: "CSD Drone Databook 2020",
  },
  {
    id: "ch-4",
    name: "CH-4",
    manufacturer: "CASC",
    country: "CN",
    category: "male",
    massKg: 1330,
    payloadKg: 345,
    flightTimeMin: 2400,
    rangeKm: 3500,
    maxSpeedKmh: 180,
    wingspanM: 18,
    source: "CSD Drone Databook 2020",
  },
  {
    id: "shahed-129",
    name: "Shahed-129",
    manufacturer: "HESA",
    country: "IR",
    category: "male",
    massKg: 450,
    flightTimeMin: 1440,
    rangeKm: 1700,
    wingspanM: 15,
    source: "CSD Drone Databook 2020",
  },
  {
    id: "mohajer-6",
    name: "Mohajer-6",
    manufacturer: "Qods Aviation",
    country: "IR",
    category: "male",
    massKg: 600,
    payloadKg: 100,
    flightTimeMin: 720,
    rangeKm: 200,
    maxSpeedKmh: 200,
    wingspanM: 10,
    source: "dronecalc/v1 database",
  },
  {
    id: "tb2",
    name: "Bayraktar TB2",
    manufacturer: "Baykar",
    country: "TR",
    category: "male",
    massKg: 650,
    payloadKg: 55,
    flightTimeMin: 1620,
    rangeKm: 300,
    maxSpeedKmh: 222,
    maxAltM: 8200,
    wingspanM: 12,
    source: "Baykar official specs",
  },
  // ── Ukrainian MALE ──
  {
    id: "pd-2",
    name: "PD-2 (UkrSpecSystems)",
    manufacturer: "UkrSpecSystems",
    country: "UA",
    category: "male",
    massKg: 25,
    payloadKg: 8.0,
    flightTimeMin: 600,
    rangeKm: 200,
    maxSpeedKmh: 100,
    notes: "VTOL, AES 256 шифрування, стійкість до РЕБ, дальність 1300 км",
    source: "dronecalc/v1 database",
  },
  {
    id: "uj-22-airborne",
    name: "UJ-22 Airborne (UkrJet)",
    manufacturer: "UkrJet",
    country: "UA",
    category: "male",
    massKg: 60,
    payloadKg: 20.0,
    flightTimeMin: 360,
    rangeKm: 800,
    maxSpeedKmh: 200,
    notes: "Стратегічний ударний БПЛА, ДВЗ, атаки вглиб РФ",
    source: "dronecalc/v1 database",
  },
  {
    id: "aq-400-scythe",
    name: "AQ-400 Scythe",
    manufacturer: "—",
    country: "UA",
    category: "male",
    massKg: 55,
    payloadKg: 32.0,
    flightTimeMin: 240,
    rangeKm: 750,
    maxSpeedKmh: 160,
    notes: "Ударний БПЛА «довгі руки», атаки нафтопереробних заводів РФ",
    source: "dronecalc/v1 database",
  },
  {
    id: "lutyy-ukrjet",
    name: '"Лютий" (UKRJET)',
    manufacturer: "UKRJET",
    country: "UA",
    category: "male",
    massKg: 150,
    payloadKg: 75.0,
    flightTimeMin: 480,
    rangeKm: 1000,
    maxSpeedKmh: 280,
    notes: "Реактивний ударний БПЛА, турбореактивний двигун",
    source: "dronecalc/v1 database",
  },
  {
    id: "gnom-ua",
    name: "MALE GNOM (UA)",
    manufacturer: "YuzhMash",
    country: "UA",
    category: "male",
    massKg: 55,
    payloadKg: 15.0,
    flightTimeMin: 600,
    rangeKm: 300,
    maxSpeedKmh: 140,
    notes: "Середній ударний БПЛА, підвіска ракет Р-60",
    source: "dronecalc/v1 database",
  },
  {
    id: "fire-point-fp2",
    name: "Fire Point FP-2 (UA)",
    manufacturer: "—",
    country: "UA",
    category: "male",
    massKg: 280,
    payloadKg: 100.0,
    flightTimeMin: 600,
    rangeKm: 750,
    maxSpeedKmh: 180,
    notes: "Ударна платформа глибокого ураження, стратегічні об'єкти РФ",
    source: "dronecalc/v1 database",
  },
  {
    id: "antonov-ua",
    name: "Antonov БПЛА (UA)",
    manufacturer: "Антонов",
    country: "UA",
    category: "male",
    massKg: 40,
    payloadKg: 10.0,
    flightTimeMin: 480,
    rangeKm: 100,
    maxSpeedKmh: 150,
    notes: "Тактичний БПЛА Антонов, ЕО/ІЧ, катапультний запуск",
    source: "dronecalc/v1 database",
  },
  {
    id: "valkyria-1",
    name: "Valkyria-1",
    manufacturer: "—",
    country: "UA",
    category: "male",
    massKg: 8,
    payloadKg: 3.0,
    flightTimeMin: 40,
    rangeKm: 50,
    maxSpeedKmh: 120,
    notes: "Важкий ударний БПЛА, серійне виробництво",
    source: "dronecalc/v1 database",
  },
  // ── Turkish MALE ──
  {
    id: "bayraktar-akinci",
    name: "Bayraktar Akıncı",
    manufacturer: "Baykar",
    country: "TR",
    category: "male",
    massKg: 5500,
    payloadKg: 1350,
    flightTimeMin: 1440,
    rangeKm: 300,
    maxSpeedKmh: 361,
    wingspanM: 20,
    notes: "2 × турбогвинтові, 24 год, ракети Roketsan SOM, AESA радар",
    source: "dronecalc/v1 database",
  },
  {
    id: "bayraktar-mini",
    name: "Bayraktar Mini UAV",
    manufacturer: "Baykar",
    country: "TR",
    category: "male",
    massKg: 2.1,
    payloadKg: 0.7,
    flightTimeMin: 60,
    rangeKm: 5,
    maxSpeedKmh: 72,
    batteryMah: 8000,
    notes: "Тактичний розвідник, електричний, ручний запуск, EO/IR",
    source: "dronecalc/v1 database",
  },
  {
    id: "tai-aksungur",
    name: "TAI Aksungur",
    manufacturer: "TAI",
    country: "TR",
    category: "male",
    massKg: 3500,
    payloadKg: 750,
    flightTimeMin: 2400,
    rangeKm: 400,
    maxSpeedKmh: 280,
    wingspanM: 24,
    notes: "Турецький MALE UCAV, 40 год, MAM-L/UMTAS, SAR+SIGINT",
    source: "dronecalc/v1 database",
  },
  {
    id: "bayraktar-tb3",
    name: "Bayraktar TB3",
    manufacturer: "Baykar",
    country: "TR",
    category: "male",
    massKg: 1400,
    payloadKg: 280,
    flightTimeMin: 1440,
    rangeKm: 280,
    maxSpeedKmh: 280,
    wingspanM: 14,
    notes: "Корабельна версія TB2, складне крило для авіаносця TCG Anadolu",
    source: "dronecalc/v1 database",
  },
  {
    id: "bayraktar-kizilelma",
    name: "Bayraktar Kızılelma",
    manufacturer: "Baykar",
    country: "TR",
    category: "male",
    massKg: 6000,
    payloadKg: 1500,
    flightTimeMin: 360,
    rangeKm: 500,
    maxSpeedKmh: 800,
    notes: "Перший турецький реактивний ударний БПЛА, AESA радар",
    source: "dronecalc/v1 database",
  },
  // ── US MALE ──
  {
    id: "mq-9-reaper",
    name: "MQ-9 Reaper",
    manufacturer: "General Atomics",
    country: "US",
    category: "male",
    massKg: 4763,
    payloadKg: 1700,
    flightTimeMin: 1080,
    rangeKm: 1850,
    maxSpeedKmh: 482,
    wingspanM: 20,
    notes: "Hellfires + GBU-12, турбопропелер 900 к.с.",
    source: "dronecalc/v1 database",
  },
  {
    id: "mq-1c-gray-eagle",
    name: "MQ-1C Gray Eagle",
    manufacturer: "General Atomics",
    country: "US",
    category: "male",
    massKg: 1633,
    payloadKg: 488,
    flightTimeMin: 1680,
    rangeKm: 400,
    maxSpeedKmh: 280,
    wingspanM: 17,
    notes: "US Army MALE, 28 год, AGM-114 Hellfire ×4, Link-16",
    source: "dronecalc/v1 database",
  },
  {
    id: "rq-4-global-hawk",
    name: "RQ-4 Global Hawk",
    manufacturer: "Northrop Grumman",
    country: "US",
    category: "male",
    massKg: 14628,
    payloadKg: 1360,
    flightTimeMin: 2160,
    rangeKm: 22780,
    maxSpeedKmh: 575,
    maxAltM: 18000,
    wingspanM: 40,
    notes: "36 год, SAR+GMTI+SIGINT, висота 18 км, моніторує Чорне море",
    source: "dronecalc/v1 database",
  },
  // ── RF MALE ──
  {
    id: "orion-kronshtadt",
    name: "Orion (Kronshtadt)",
    manufacturer: "Kronshtadt",
    country: "RU",
    category: "male",
    massKg: 1000,
    payloadKg: 200,
    flightTimeMin: 1440,
    rangeKm: 300,
    maxSpeedKmh: 200,
    wingspanM: 16,
    notes: "Важкий ударний БПЛА РФ, 24 год, ракети X-25, аналог MQ-9",
    source: "dronecalc/v1 database",
  },
  {
    id: "forpost-ru",
    name: "Forpost-RU",
    manufacturer: "UVZ",
    country: "RU",
    category: "male",
    massKg: 375,
    payloadKg: 30,
    flightTimeMin: 1080,
    rangeKm: 250,
    maxSpeedKmh: 200,
    wingspanM: 8,
    notes: "Ліцензійна копія IAI Searcher II, розвідка і коригування вогню",
    source: "dronecalc/v1 database",
  },
  {
    id: "forpost-m",
    name: "Forpost-M (РФ)",
    manufacturer: "UVZ",
    country: "RU",
    category: "male",
    massKg: 500,
    payloadKg: 120,
    flightTimeMin: 600,
    rangeKm: 250,
    maxSpeedKmh: 200,
    wingspanM: 9,
    notes: "Модернізований ISR/ударний, вітчизняний двигун, EO/IR/SAR",
    source: "dronecalc/v1 database",
  },
  {
    id: "geran-3",
    name: "Герань-3 / Geran-3 (РФ)",
    manufacturer: "—",
    country: "RU",
    category: "male",
    massKg: 300,
    payloadKg: 50,
    flightTimeMin: 720,
    rangeKm: 2200,
    maxSpeedKmh: 500,
    notes: "Апгрейд Shahed-136, турбофан, Mesh WiFi роєва координація, AI (2025)",
    source: "dronecalc/v1 database",
  },
  // ── Iranian MALE ──
  {
    id: "mohajer-10",
    name: "Mohajer-10 (Іран)",
    manufacturer: "Qods Aviation",
    country: "IR",
    category: "male",
    massKg: 700,
    payloadKg: 300,
    flightTimeMin: 1440,
    rangeKm: 2000,
    maxSpeedKmh: 210,
    wingspanM: 15,
    notes: "Новітній іранський MALE 2023, 24 год, EO/IR/SAR",
    source: "dronecalc/v1 database",
  },
  {
    id: "shahed-149-gaza",
    name: "Shahed-149 Gaza",
    manufacturer: "HESA",
    country: "IR",
    category: "male",
    massKg: 3000,
    payloadKg: 500,
    flightTimeMin: 1200,
    rangeKm: 2000,
    maxSpeedKmh: 250,
    wingspanM: 22,
    notes: "Стратегічний БПЛА, турбопропелер, ракети Sadid-345, 20 год",
    source: "dronecalc/v1 database",
  },
  // ── Israeli MALE ──
  {
    id: "iai-harop-male",
    name: "IAI Harop (MALE)",
    manufacturer: "IAI",
    country: "IL",
    category: "male",
    massKg: 135,
    payloadKg: 23,
    flightTimeMin: 360,
    rangeKm: 1000,
    maxSpeedKmh: 417,
    wingspanM: 3,
    notes: "Барражуючий боєприпас, пасивна ГСН, 6 год барражування",
    source: "dronecalc/v1 database",
  },
  {
    id: "hermes-450",
    name: "Elbit Hermes 450",
    manufacturer: "Elbit Systems",
    country: "IL",
    category: "male",
    massKg: 550,
    payloadKg: 150,
    flightTimeMin: 1020,
    rangeKm: 200,
    maxSpeedKmh: 176,
    wingspanM: 10,
    notes: "17 год польоту, EO/IR/SAR, Spike ER, бригадний рівень",
    source: "dronecalc/v1 database",
  },
  {
    id: "hermes-900",
    name: "Elbit Hermes 900",
    manufacturer: "Elbit Systems",
    country: "IL",
    category: "male",
    massKg: 1180,
    payloadKg: 300,
    flightTimeMin: 1080,
    rangeKm: 300,
    maxSpeedKmh: 220,
    wingspanM: 15,
    notes: "MALE ISR, Rotax 914, EO/IR/SAR, 18 год",
    source: "dronecalc/v1 database",
  },
  {
    id: "iai-heron-1",
    name: "IAI Heron 1",
    manufacturer: "IAI",
    country: "IL",
    category: "male",
    massKg: 1150,
    payloadKg: 250,
    flightTimeMin: 2520,
    rangeKm: 350,
    maxSpeedKmh: 207,
    wingspanM: 16,
    notes: "42 год польоту, SAR/EO/SIGINT, NATO STANAG 4671",
    source: "dronecalc/v1 database",
  },
  // ── Chinese MALE ──
  {
    id: "wing-loong-ii",
    name: "Wing Loong II (AVIC)",
    manufacturer: "AVIC",
    country: "CN",
    category: "male",
    massKg: 4200,
    payloadKg: 480,
    flightTimeMin: 1200,
    rangeKm: 1500,
    maxSpeedKmh: 370,
    wingspanM: 20,
    notes: "Покращений MALE UCAV, TL-1/TL-2/CM-102, турбогвинтовий TPE331-10G",
    source: "dronecalc/v1 database",
  },
  {
    id: "wz-7-soaring-dragon",
    name: "WZ-7 Soaring Dragon",
    manufacturer: "CAIG",
    country: "CN",
    category: "male",
    massKg: 7500,
    payloadKg: 650,
    flightTimeMin: 600,
    rangeKm: 7000,
    maxSpeedKmh: 750,
    maxAltM: 18000,
    wingspanM: 25,
    notes: "Китайський стратегічний ISR flying wing, аналог RQ-4",
    source: "dronecalc/v1 database",
  },
];

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------
export const ALL_DRONES: DroneSpec[] = [
  ...FPV_ATTACK,
  ...ISR_MULTIROTOR,
  ...ISR_FIXED,
  ...MILITARY_UAV,
];

export const CATEGORY_LABELS: Record<DroneCategory, { en: string; ua: string }> = {
  "fpv-attack": { en: "FPV Attack", ua: "FPV Ударні" },
  "isr-multirotor": { en: "ISR Multirotor", ua: "РЕБ/Розвідка (Мультиротор)" },
  "isr-fixed": { en: "ISR Fixed-wing", ua: "Розвідка + Барражуючі (Літак)" },
  male: { en: "MALE / Strike", ua: "MALE / Ударні" },
};

export const COUNTRY_FLAGS: Record<string, string> = {
  RU: "🇷🇺",
  CN: "🇨🇳",
  US: "🇺🇸",
  UA: "🇺🇦",
  TR: "🇹🇷",
  IR: "🇮🇷",
  IL: "🇮🇱",
  PL: "🇵🇱",
  INT: "🌐",
};
